-- create database customer_behavior;
use customer_behavior;
select * from customer limit 20;

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue 
from customer
group by gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount from customer
where discount_applied ='yes' and purchase_amount >= (select AVG(purchase_amount) from Customer);


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased ,ROUND(avg(review_rating),2) as"Average Product Rating " from customer
group by item_purchased
order by avg(review_rating) desc
limit 6;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,
round(avg(purchase_amount),2) AS avg_purchase
FROM customer
where shipping_type in ('standard','express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customer,
ROUND(avg(purchase_amount),2) as avg_spend,
ROUND(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100/ COUNT(*)) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;



-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

with customer_type as(
select customer_id, previous_purchases,
CASE 
WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 8 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment
FROM customer
)
select customer_segment, COUNT(*) AS "Number of customer"
from customer_type
GROUP BY Customer_Segment;

-- Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
count(*) as total_orders,
row_number() over(PARTITION BY Category ORDER BY COUNT(*) DESC) AS item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
COUNT(*) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;



-- Q10. What is the revenue contribution of each age Loup?

SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
order by total_revenue desc;
